import PushNotification from 'react-native-push-notification';

const remoteNotification = data => {
  PushNotification.localNotification({
    channelId: '12345',
    title: data.notification.title,
    message: data.notification.body,
  });
};

const localNotification = () => {
  PushNotification.localNotification({
    channelId: '12345', // (required) channelId, if the channel doesn't exist, notification will not trigger.
    ticker: 'My Notification Ticker', // (optional)
    largeIcon: 'ic_launcher', // (optional) default: "ic_launcher". Use "" for no large icon.
    largeIconUrl: 'https://source.unsplash.com/400x400?nature', // (optional) default: undefined
    smallIcon: 'ic_notification', // (optional) default: "ic_notification" with fallback for "ic_launcher". Use "" for default small icon.
    bigText: 'My big text that will be shown when notification is expanded', // (optional) default: "message" prop
    subText: 'This is a subText', // (optional) default: none
    bigPictureUrl: 'https://source.unsplash.com/400x400?nature', // (optional) default: undefined
    bigLargeIcon: 'ic_launcher', // (optional) default: undefined
    bigLargeIconUrl: 'https://source.unsplash.com/400x400?nature', // (optional) default: undefined
    vibrate: true, // (optional) default: true
    priority: 'high',
    visibility: 'private', // (optional) set notification visibility, default: private
    ignoreInForeground: false, // (optional) if true, the notification will not be visible when the app is in the foreground (useful for parity with how iOS notifications appear). should be used in combine with `com.dieam.reactnativepushnotification.notification_foreground` setting
    messageId: 'google:message_id',
    /* iOS only properties */
    category: 'shopping', // (optional) default: empty string
    subtitle: 'My Notification Subtitle', // (optional) smaller title below notification title

    /* iOS and Android properties */
    id: 0, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
    title: 'My Notification Title', // (optional)
    message: 'My Notification Message', // (required)
    playSound: true, // (optional) default: true
    soundName: 'notification.mp3', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
  });
};

export {remoteNotification, localNotification};
